# Generated by Django 4.0.4 on 2022-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_debater_institution_motion_round_tournament_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
