# Generated by Django 4.0.4 on 2022-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_institution_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
